# Generated by Django 4.2.6 on 2024-01-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='nome_status',
            field=models.CharField(default='sem status', max_length=128),
            preserve_default=False,
        ),
    ]
